name: flutter_app_init
version: 0.8.0
environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"
dependencies:
  flutter:
    sdk: flutter
  easy_localization: 3.0.4
  sentry_flutter: 7.16.1
  realm: 1.9.0
  loader_overlay: 4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  merciless_flutter_lints:
    git:
      url: https://github.com/EdgarJan/merciless_flutter_lints.git
      ref: '41868a7'
flutter: