name: flutter_app_init
version: 0.1.0
environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'
  flutter: ">=3.12.0-1.1.pre"
dependencies:
  flutter:
    sdk: flutter
  easy_localization: 3.0.2
  sentry_flutter: 7.8.0
  realm: 1.2.0
  loader_overlay: 2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: