name: flutter_app_init
version: 1.1.1
environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: ">=3.24.3"
dependencies:
  flutter:
    sdk: flutter
  easy_localization: 3.0.7
  # sentry_flutter: 8.2.0
  realm: 3.4.1
  loader_overlay: 4.0.2+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  merciless_flutter_lints:
    git:
      url: https://github.com/EdgarJan/merciless_flutter_lints.git
      ref: '41868a7'