name: flutter_app_init
version: 1.0.0
environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=3.22.1"
dependencies:
  flutter:
    sdk: flutter
  easy_localization: 3.0.7
  sentry_flutter: 8.2.0
  realm: 2.3.0
  loader_overlay: 4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  merciless_flutter_lints:
    git:
      url: https://github.com/EdgarJan/merciless_flutter_lints.git
      ref: '41868a7'
flutter: