name: flutter_app_init
version: 0.2.3
environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.10.5"
dependencies:
  flutter:
    sdk: flutter
  easy_localization: 3.0.2
  sentry_flutter: 7.8.0
  realm: 1.3.0
  loader_overlay: 2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: