name: flutter_app_init
version: 0.4.3
environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=3.13.6"
dependencies:
  flutter:
    sdk: flutter
  easy_localization: 3.0.3
  sentry_flutter: 7.10.1
  realm: 1.5.0
  loader_overlay: 2.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.3
flutter: